theme: minima
title: Fairer AI for Skin Cancer Detection - A Deep Learning Approach
description: Mitigating skin tone bias in skin lesion classification using Neural Style Transfer.
author: Matthias Schultze-Kraft
