theme: minima
title: Toward Fairer Skin Lesion Classification with Deep Learning
description: Mitigating skin tone bias in skin lesion classification using Neural Style Transfer.
author: Matthias Schultze-Kraft
