theme: minima
title: Skin Lesion Classification with Neural Style Transfer
description: A deep learning project combining dataset augmentation, transfer learning, and web deployment.
author: Matthias Schultze-Kraft
