theme: minima
title: Skin Lesion Classification across all Skin Tones
description: Mitigating skin tone bias in skin lesion classification using Neural Style Transfer.
author: Matthias Schultze-Kraft
